permalink: "/articles/:year/:month/:day/:title"
exclude: ["README.markdown"]
lsi: false
safe: true

baseurl: ""
title: The Irssi Project
name: Irssi Core Team
email: staff@irssi.org
url: "http://irssi.github.io"
