permalink: "/:year/:month/:day/:title"
exclude: ["README.markdown"]
lsi: false
safe: true

baseurl: ""
url: "http://irssi.github.io"

title: Irssi
project: The Irssi Project
description: The Client of the Future
name: Irssi Core Team
email: staff@irssi.org

paginate: 8
paginate_path: "news/:num/"
