permalink: "/:year/:month/:day/:title/"
exclude: ["README.markdown"]
lsi: false
safe: true
future: true
baseurl: ""
excerpt_separator: "\n\n\n"


title: Irssi
project: The Irssi Project
description: The Client of the Future
name: Irssi Core Team
email: staff@irssi.org

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

whitelist:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

paginate: 8
paginate_path: "news/:num/"

collections:
  articles:
    output: true
    permalink: "/articles/:title/"
  security_html:
    output: true
    permalink: "/security/html/:title/"
  security:
    output: true
    permalink: "/security/:title.txt"

defaults:
 - scope:
     path: "_security_html"
   values:
     layout: security_html
 -
   scope:
     path: "_security"
   values:
     layout: security_txt
