on:
  push:
    branches:
      - jekyll

jobs:
  rebuild-pages:
    if: github.repository == 'irssi/irssi.github.io'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'pages.yml',
              ref: 'main'
            })